apiVersion: v1
kind: Service
metadata:
  name: {{ include "frontend.fullname" . }}
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - targetPort: 80
      name: http
      port: {{ .Values.service.port | default 80 }}
  selector:
    {{- include "frontend.selectorLabels" . | nindent 4 }}
