apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-management
spec:
  destination:
    namespace: manage
    server: https://kubernetes.default.svc
  source:
    path: ./cluster-manage-argo
    repoURL: https://github.com/MoAbouDeif/DeifOps-Calculator.git
    targetRevision: main
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
      enabled: true
    syncOptions:
      - CreateNamespace=true
