secret:
  secretName: mysql-secret
  data:
    mysql-password: bXlwYXNz
    mysql-replication-password: cmVwbGljYXBhc3M=
    mysql-root-password: cm9vdHBhc3M= 
  
---

storageClass:
  name: gp3
  provisioner: 'ebs.csi.aws.com'
  parameters:
    type: gp3
    fsType: ext4
  reclaimPolicy: Retain
  volumeBindingMode: WaitForFirstConsumer

---

frontend:
  replicaCount: 2
  image:
    repository: deifops/calc-frontend
    pullPolicy: IfNotPresent
    tag: 1.20.0
  env:
    - name: SERVER_NAME
      value: calc.deifops.click
    - name: BACKEND_HOST
      value: deifops-backend
    - name: BACKEND_PORT
      value: '5000'

  imagePullSecrets: []
  livenessProbe:
    httpGet:
      path: /healz/
      port: 80
  readinessProbe:
    httpGet:
      path: /probe/
      port: 80

  nameOverride: ''
  fullnameOverride: deifops-frontend

  service:
    type: NodePort 
    port: ""

  ingress:
    enabled: true
    className: alb
    annotations:
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/healthcheck-path: /healz/
      alb.ingress.kubernetes.io/target-type: ip
      # alb.ingress.kubernetes.io/ssl-redirect: "443"
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
      external-dns.alpha.kubernetes.io/ttl: "60"
      external-dns.alpha.kubernetes.io/ingress-hostname-source: defined-hosts-only
      # cert-manager.io/cluster-issuer: letsencrypt-prod
      # alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:eu-central-1:993260646119:certificate/xxxxxx
      alb.ingress.kubernetes.io/group.name: deifops
    hosts:
      - host: calc.deifops.click
        paths:
          - path: /
            pathType: Prefix

  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 50

---

backend:
  replicaCount: 2
  image:
    repository: deifops/calc-backend
    pullPolicy: IfNotPresent
    tag: 1.16.0
  imagePullSecrets: []
  nameOverride: ''
  fullnameOverride: deifops-backend
  service:
    type: ClusterIP
    port: 5000
  livenessProbe:
    httpGet:
      path: /
      port: 5000
  readinessProbe:
    httpGet:
      path: /
      port: 5000
  env:
    - name: MYSQL_HOST
      value: deifops-mysql-headless
    - name: MYSQL_USER
      value: calc_user
    - name: MYSQL_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysql-secret
          key: mysql-password
    - name: MYSQL_DB
      value: calc_db
    - name: ALLOWED_ORIGINS
      value: 'https://calc.deifops.click'

---

mysql:
  fullname: ''
  fullnameOverride: deifops-mysql
  architecture: standalone
  auth:
    rootPassword: ''
    createDatabase: true
    database: calc_db
    username: calc_user
    password: ''
    replicationUser: 'replicator'
    replicationPassword: ''
    existingSecret: mysql-secret
  primary:
    name: primary
    persistence:
      enabled: true
      existingClaim: ''
      storageClass: gp3
      accessModes:
        - ReadWriteOnce
      size: 8Gi
      selector: {}
  secondary:
    name: secondary
    replicaCount: 1
    persistence:
      enabled: true
      existingClaim: ''
      storageClass: gp3
      accessModes:
        - ReadWriteOnce
      size: 8Gi
      selector: {}
