apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollouts
spec:
  destination:
    namespace: argo
    server: https://kubernetes.default.svc
  source:
    path: ''
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 2.40.3
    chart: argo-rollouts
    helm:
      parameters:
        - name: installCRDs
          value: 'false'
        - name: dashboard.enable
          value: 'true'
      values: |
        dashboard:
          ingress:
            enabled: true
            ingressClassName: nginx
            paths: ["rollouts.argo.local"]


  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      enabled: true
    syncOptions:
      - CreateNamespace=true
