apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
spec:
  destination:
    namespace: argo
    server: https://kubernetes.default.svc
  source:
    path: ''
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 8.3.5
    chart: argo-cd
    helm:
      values: |
        global:
          domain: cd.argo.local
        configs:
          params:
            server.insecure: 'true'
        server:
          ingress:
            enable: 'true'
            ingressClassName: nginx
          ingressGrpc:
            enable: 'true'
            ingressClassName: nginx            
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
      enabled: true
    syncOptions:
      - CreateNamespace=true
