apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  source:
    path: ''
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 77.5.0
    chart: kube-prometheus-stack
    helm:
      values: |
        alertmanager:
          ingress:
            enabled: true
            ingressClassName: nginx
            hosts: ["alert.prometheus.local"]
        grafana:
          ingress:
            enabled: true
            ingressClassName: nginx
            hosts: ["grafana.prometheus.local"]
        prometheus:
          ingress:
            enabled: true
            ingressClassName: nginx
            hosts: ["prometheus.local"]
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      enabled: true
    syncOptions:
      - CreateNamespace=true
