apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: test-deifops-canary
  labels:
    app: test-deifops-canary
spec:
  replicas: 4
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: test-deifops-canary
  strategy:
    canary:
      stableService: test-deifops-active   # ✅ required
      canaryService: test-deifops-canary   # ✅ required
      scaleDownDelaySeconds: 60
      autoPromotionEnabled: false
      steps:
      - setWeight: 30
      - pause: {}
      - setWeight: 60
      - pause: {}
      - setWeight: 100
      - pause: {}
      trafficRouting:
        traefik:
          weightedTraefikServiceName: traefik-service
  template:
    metadata:
      labels:
        app: test-deifops-canary
    spec:
      containers:
      - name: nginx
        image: docker.io/kostiscodefresh/gitops-canary-app:v1.0
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 250m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 128Mi

---
apiVersion: v1
kind: Service
metadata:
  name: test-deifops-active
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: test-deifops-canary   # rollout will manage pod-template-hash
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: test-deifops-canary
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: test-deifops-canary   # rollout will manage pod-template-hash
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: traefik.containo.us/v1alpha1
kind: TraefikService
metadata:
  name: traefik-service
  namespace: default
spec:
  weighted:
    services:
      - name: test-deifops-active
        port: 80
        weight: 100
      - name: test-deifops-canary
        port: 80
        weight: 0

