apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: test-deifops-canary
  namespace: default
  labels:
    app: test-deifops-canary
spec:
  replicas: 4
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: test-deifops-canary
  strategy:
    canary:
      activeService: test-deifops-active
      canaryService: test-deifops-canary
      autoPromotionEnabled: false
      scaleDownDelaySeconds: 60
      trafficRouting:
        traefik:
          weightedTraefikServiceName: traefik-service   # must exist as TraefikService
      steps:
        - setWeight: 30
        - pause: {}
        - setWeight: 60
        - pause: {}
        - setWeight: 100
        - pause: {}
  template:
    metadata:
      labels:
        app: test-deifops-canary
    spec:
      containers:
      - name: nginx
        image: docker.io/kostiscodefresh/gitops-canary-app:v1.0
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: test-deifops-active
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: test-deifops-canary   # rollout will manage pod-template-hash
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: test-deifops-canary
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: test-deifops-canary   # rollout will manage pod-template-hash
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: traefik.io/v1alpha1
kind: TraefikService
metadata:
  name: traefik-service
  namespace: default
spec:
  weighted:
    services:
      - name: test-deifops-active
        port: 80
        weight: 100
      - name: test-deifops-canary
        port: 80
        weight: 0
